version: '3'

services:
  internal_gis_map:
    build:
      context: ./map
    networks:
      - tipc_stg
    volumes:
      - ./map/index.html:/index.html
  
  default_restful_api:
    build:
      context: ./api
    ports:
      - '5000:5000'
    networks:
      - tipc_stg

networks:
  tipc_stg: